"""update iteration_logs schema

Revision ID: c98f53a427bc
Revises: 07c2e835a9db
Create Date: 2025-09-23 13:29:33.941654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98f53a427bc'
down_revision: Union[str, None] = '07c2e835a9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_evals_spec_id'), table_name='evals')
    op.drop_index(op.f('idx_feedback_logs_spec_id'), table_name='feedback_logs')
    op.drop_index(op.f('idx_iteration_logs_session_id'), table_name='iteration_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_iteration_logs_session_id'), 'iteration_logs', ['session_id'], unique=False)
    op.create_index(op.f('idx_feedback_logs_spec_id'), 'feedback_logs', ['spec_id'], unique=False)
    op.create_index(op.f('idx_evals_spec_id'), 'evals', ['spec_id'], unique=False)
    # ### end Alembic commands ###
