version: '3.8'

services:
  prompt-to-json-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
      - "8501:8501"
    environment:
      - DATABASE_URL=sqlite:///data/prompt_to_json.db
      - LOG_LEVEL=INFO
      - ENABLE_ANALYTICS=true
      - ENABLE_CORS=true
      - RATE_LIMIT=1000
      - WEB_PORT=5000
    volumes:
      - prompt_data:/app/data
      - prompt_logs:/app/logs
      - prompt_outputs:/app/spec_outputs
      - prompt_reports:/app/reports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  prompt-to-json-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["python", "-m", "streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    ports:
      - "8502:8501"
    environment:
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=none
      - STREAMLIT_SERVER_HEADLESS=true
    volumes:
      - prompt_data:/app/data
      - prompt_logs:/app/logs
      - prompt_outputs:/app/spec_outputs
    restart: unless-stopped
    depends_on:
      - prompt-to-json-api

volumes:
  prompt_data:
  prompt_logs:
  prompt_outputs:
  prompt_reports: