name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests before deploy
        run: |
          pytest tests/ -v --tb=short
        env:
          DATABASE_URL: sqlite:///test.db
          API_KEY: test-key
          JWT_SECRET: test-jwt-secret
      
      - name: Build Docker image
        run: |
          docker build -t prompt-agent:production .
      
      - name: Deploy to Render
        run: |
          echo "🚀 Deploying to Render.com..."
          echo "Production URL: https://prompt-to-json-backend.onrender.com"
          echo "Deployment triggered via git push to main branch"
          echo "Render will automatically build and deploy the latest commit"
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      
      - name: Health check after deploy
        run: |
          echo "⏳ Waiting for deployment to complete..."
          sleep 60
          echo "🔍 Running health check..."
          curl -f https://prompt-to-json-backend.onrender.com/health || echo "Health check failed - manual verification needed"
      
      - name: Notify deployment status
        run: |
          echo "✅ Deployment completed!"
          echo "🌐 Production URL: https://prompt-to-json-backend.onrender.com"
          echo "📊 Metrics: https://prompt-to-json-backend.onrender.com/metrics"
          echo "📚 API Docs: https://prompt-to-json-backend.onrender.com/docs"